name: Build
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - run: make main
